// document.writeln("<!DOCTYPE html>");
// document.writeln("<html lang=\'en\'>");
// document.writeln("<head>");
document.writeln("    <meta charset=\'utf-8\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1\'>");
document.writeln("    <script src=\'../js/jquery-1.8.0.js\'></script>");
// document.writeln("    <script src=\'../js/jquery-1.4.2.min.js\'></script>");
document.writeln("    <link rel=\'stylesheet\' href=\'../js/layui/css/layui.css\'>");
document.writeln("    <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->");
document.writeln("    <!--[if lt IE 9]>");
document.writeln("    <script src=\'../js/IE8.js\'></script>");
document.writeln("    <script src=\'../js/html5shiv.min.js\'></script>");
document.writeln("    <script src=\'../js/respond.min.js\'></script>");
document.writeln("    <script src=\'../js/PIE/PIE.js\'></script>");
document.writeln("    <![endif]-->");
document.writeln("    <link rel=\'stylesheet\' href=\'../css/base.css\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'../css/reset.css\'>");
document.writeln("    <script src=\'../js/layui/layui.js\'></script>");
document.writeln("    <script src=\'../js/echarts.min.js\'></script>");
document.writeln("    <link rel=\'stylesheet\' href=\'../icon/iconfont.css\'>");
// document.writeln("    <script src=\'../icon/iconfont.js\'></script>");
document.writeln("    <script src=\'../js/loginValidate.js\'></script>");
// document.writeln("</head>");
// document.writeln("<body>");
// document.writeln("</body>");
// document.writeln("</html>");